name: Docker Image Scan

on:
  push:
    branches:
      - main  

jobs:
  scan:
    runs-on: ubuntu-latest  

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.UserIDDockerHub }}
        password: ${{ secrets.PassWordDockerHub }}
 
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  

    - name: Run Docker Scout vulnerability scan
      uses: docker/scout-action@v1  
      with:
        command: cves  
        image: imraahatikah6827/https
        summary: true
        format: table  
        github-token: ${{ secrets.DOCKERTALKINGPASSWORD }}
        write-comment: true
